#### Exercise 1
Create a Pandas DataFrame from a dictionary. The dictionary keys should be `Crop`, `Yield_per_Acre`, and `Country`, and the values should be lists, as shown in the data below:

- Crop: `['Wheat', 'Corn', 'Rice', 'Soybean']`
- Yields per acre (in tons): `[3, 4.5, 5, 2.8]`
- Country: `['USA', 'China', 'India', 'Brazil']`

In [1]:
import pandas as pd
import numpy as np

In [20]:
# Creating the columns and values using the data
agric_data = {
    'Crop': ['Wheat', 'Corn', 'Rice', 'Soybean'],
    'Yields_per_Acre': [3, 4.5, 5, 2.8],
    'Country': ['USA', 'China', 'India', 'Brasil']
}

# Creating the dataframe for the agriculture data
agric_df = pd.DataFrame(data=agric_data)

# Printing the DataFrame
agric_df

      Crop  Yields_per_Acre Country
0    Wheat              3.0     USA
1     Corn              4.5   China
2     Rice              5.0   India
3  Soybean              2.8  Brasil

#### Exercise 2
Using the DataFrame we created in **Exercise 1**, return only observations for index values 1 and 2 from the dataset.

In [21]:
# Observations for index values 1 and 2
agric_df.iloc[1:3]

   Crop  Yields_per_Acre Country
1  Corn              4.5   China
2  Rice              5.0   India

#### Exercise 3
- Using the Numpy library, create a 3x2 array named `tree_array` to store informations for different tree species as follows:

    [[30, 25], [60, 30], [25, 20]].
- Use the array to create a DataFrame with the following columns: `Max_Height_m`, and `Growth_rate_cm_per_year`, and the following index: `Maple`, `Pine` and `Birch`.

In [23]:
# Creating the numpy 3x2 array
tree_array = np.array([[30, 25], [60, 30], [25, 20]])

# Defining the column names
columns = ['Max_Height_m', 'Growth_rate_cm_per_year']

# Defining the index
index = ['Maple', 'Pine', 'Birch']

# Creating the DataFrame
tree_df = pd.DataFrame(data=tree_array, columns=columns, index=index)

#Printing the DataFrame
print(tree_df)

       Max_Height_m  Growth_rate_cm_per_year
Maple            30                       25
Pine             60                       30
Birch            25                       20

#### Exercise 4
Using the DataFrame in Exercise 3, display the Max_Height_m and Growth_rate_cm_per_year columns for the `Pine` tree.

In [24]:
# Displaying the Maximum Height and Growth rate for Pine
Pine_data = tree_df.loc['Pine']

# Printing the pine data
print(Pine_data)

Max_Height_m               60
Growth_rate_cm_per_year    30
Name: Pine, dtype: int64

#### Exercise 5

- We have a dataset named `Animals.csv` that stores information about a variety of animal species. Use Pandas to load the CSV file into a DataFrame called `animals_df`. 

- Display the first 5 rows of the DataFrame.

**NB:** Use this link to access the dataset: https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv

In [25]:
# loading the animals csv into the DataFrame
animals_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv', index_col='Species')

# Accessing the first 5 rows of the dataset
animals_df.head()

,Average Lifespan (Years),Habitat,Conservation Status
Species,,,
African Elephant,60,Grasslands,Vulnerable
Bengal Tiger,15,Forests,Endangered
Blue Whale,80,Ocean,Endangered
Giant Panda,20,Temperate Forest,Vulnerable
Komodo Dragon,30,Islands,Vulnerable

#### Exercise 6
Using the DataFrame we have created in Exercise 5, access and display informations on animals that are listed as `Critically Endangered` in the `Conservation Status` column.

In [28]:
# Creating a new DataFrame based on a condition
Critically_endangered = animals_df[animals_df['Conservation Status'] == 'Critically Endangered']

# Accessing the critically endangered data
Critically_endangered

           Average Lifespan (Years)      Habitat    Conservation Status
Species
Orangutan                        35  Rainforests  Critically Endangered