In [1]:
import pandas as pd
import numpy as np

We are Using the dataset named `Animals.csv` that stores information about a variety of animal species.

dataset: https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv

In [12]:
animals_data = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv', index_col= 'Species')

animals_data.head()

,Average Lifespan (Years),Habitat,Conservation Status
Species,,,
African Elephant,60,Grasslands,Vulnerable
Bengal Tiger,15,Forests,Endangered
Blue Whale,80,Ocean,Endangered
Giant Panda,20,Temperate Forest,Vulnerable
Komodo Dragon,30,Islands,Vulnerable

#### Exercise 1
Filter the dataset to show only species that have an `Average Lifespan (Years)` greater than 20 and are classified as `Vulnerable` in the `Conservation Status`.

In [ ]:
#Filtering the data based on the two conditions
longlived_and_vulnerable = animals_data[(animals_data['Average Lifespan (Years)'] > 20) & (animals_data['Conservation Status'] == 'Vulnerable')]

# Displaying the filtered data
longlived_and_vulnerable

                  Average Lifespan (Years)     Habitat Conservation Status
Species
African Elephant                        60  Grasslands          Vulnerable
Komodo Dragon                           30     Islands          Vulnerable
Polar Bear                              25      Arctic          Vulnerable

#### Exercise 2
**a.)** Create a new column `Lifespan in Months` by converting the `Average Lifespan (Years)` to months

In [ ]:
def years_to_months(x):
    """ This function multiplies the value of x by 12"""
    return x * 12

# creating the Lifespan in Months column by applying the function 
# to the Average Lifespan (Years) column
animals_data['Lifespan in Months'] = years_to_months(animals_data['Average Lifespan (Years)'])

# Displaying the data
animals_data.head()

,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months
Species,,,,
African Elephant,60,Grasslands,Vulnerable,720
Bengal Tiger,15,Forests,Endangered,180
Blue Whale,80,Ocean,Endangered,960
Giant Panda,20,Temperate Forest,Vulnerable,240
Komodo Dragon,30,Islands,Vulnerable,360

**b.)** Delete the `Lifespan in Months` from the DataFrame.

In [ ]:
# Using the .drop function to delete the Lifespan in Months column
animals_data = animals_data.drop('Lifespan in Months', axis=1, inplace=True)

animals_data.head()

,Average Lifespan (Years),Habitat,Conservation Status
Species,,,
African Elephant,60,Grasslands,Vulnerable
Bengal Tiger,15,Forests,Endangered
Blue Whale,80,Ocean,Endangered
Giant Panda,20,Temperate Forest,Vulnerable
Komodo Dragon,30,Islands,Vulnerable

#### Exercise 3
**a.)** Filter the DataFrame to include only species with `Average Lifespan (Years)` **greater than 50 years**. Store the result in a new DataFrame `Long_lived_species`.

In [ ]:
# Creating a dataframe for older than 50 years species
Long_lived_species = animals_data[animals_data['Average Lifespan (Years)'] > 50]

# Displaying the data
Long_lived_species

,Average Lifespan (Years),Habitat,Conservation Status
Species,,,
African Elephant,60,Grasslands,Vulnerable
Blue Whale,80,Ocean,Endangered
Green Sea Turtle,80,"Oceans, Beaches",Endangered

**b.)** Using the `apply` and `lambda` functions, convert the `Average Lifespan (Years)` of all species into float data type in `Long_lived_species`.

In [31]:
# Converting the datatype in the Average Lifespan (Years) column to float
# Using lambda and apply functions
Long_lived_species['Average Lifespan (Years)'] = Long_lived_species['Average Lifespan (Years)'].apply(lambda x: float(x))

# Displaying the new datatype
Long_lived_species.info()

<class 'pandas.DataFrame'>
Index: 3 entries, African Elephant to Green Sea Turtle
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Average Lifespan (Years)  3 non-null      float64
 1   Habitat                   3 non-null      str
 2   Conservation Status       3 non-null      str
dtypes: float64(1), str(2)
memory usage: 204.0+ bytes

#### Exercise 4
List all columns for species that have the string "`Endangered`" as part of their conservation status.

In [ ]:
# Selecting columns with endangered species
Endangered_species = animals_data[animals_data['Conservation Status'] == 'Endangered']

# Displaying the results
Endangered_species

,Average Lifespan (Years),Habitat,Conservation Status
Species,,,
Bengal Tiger,15,Forests,Endangered
Blue Whale,80,Ocean,Endangered
Green Sea Turtle,80,"Oceans, Beaches",Endangered

#### Exercise 5
list the mean `Average Lifespan (Years)` of species for each `Habitat` in descending order.

In [46]:
# Calculating the mean Average Lifespan (Years) for each habitat in descending order

Mean_lifespan_per_habitat = animals_data.groupby('Habitat')['Average Lifespan (Years)'].mean().sort_values(ascending=False)

# Displaying the results
Mean_lifespan_per_habitat

Habitat
Oceans, Beaches       80.0
Ocean                 80.0
Grasslands            60.0
Rainforests           35.0
Islands               30.0
Arctic                25.0
Antarctic             20.0
Temperate Forest      20.0
Forests, Seacoasts    20.0
Forests               15.0
Mountain Ranges       15.0
Savanna               14.0
Eucalyptus Forests    13.0
Forests, Tundra        8.0
Various                5.0
Name: Average Lifespan (Years), dtype: float64

#### Exercise 6
Create a column `Threat Level` that categorises species into `High`, `Medium`,  or `Low` based on their `Conservation Status`:

- **High** for `Critically Endangered` and `Endangered`
- **Medium** for `Vulnerable` and `Near Threatened`
- **Low** for `Least Concern`

In [68]:
def threat_status(status):
    """Classifies the status into different threat level"""
    if status in ['Critically Endangered', 'Endangered']:
        return 'High'
    elif status in ['Vulnerable', 'Near Threatened']:
        return 'Medium'
    else:
        return 'Low'

# Applying the function on the Conservation status column      
animals_data['Threat Level'] = animals_data['Conservation Status'].apply(threat_status)

# Displaying the result
animals_data

,Average Lifespan (Years),Habitat,Conservation Status,Threat Level
Species,,,,
African Elephant,60,Grasslands,Vulnerable,Medium
Bengal Tiger,15,Forests,Endangered,High
Blue Whale,80,Ocean,Endangered,High
Giant Panda,20,Temperate Forest,Vulnerable,Medium
Komodo Dragon,30,Islands,Vulnerable,Medium
Polar Bear,25,Arctic,Vulnerable,Medium
Red Fox,5,Various,Least Concern,Low
Emperor Penguin,20,Antarctic,Near Threatened,Medium
Koala,13,Eucalyptus Forests,Vulnerable,Medium
Orangutan,35,Rainforests,Critically Endangered,High
Snow Leopard,15,Mountain Ranges,Vulnerable,Medium
Bald Eagle,20,"Forests, Seacoasts",Least Concern,Low
African Lion,14,Savanna,Vulnerable,Medium
Green Sea Turtle,80,"Oceans, Beaches",Endangered,High
Gray Wolf,8,"Forests, Tundra",Least Concern,Low